# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Automate Pull and Push request automation

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

# permissions:
#   contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #Try different versions of Python
        python-version: [ 3.6, 3.8, 3.9 ]
    steps:
      - name: update repo
        uses: actions/checkout@v2
      - name: Set Up Python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Extract Economic Twitter Data from zip to json
        run: unzip data/Economic_Twitter_Data.zip -d data/

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: python -m unittest tests.test_clean_df
      - name: print results
        run: echo "This action automated check ${{jobs.status}}."
